name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            SLACK_SIGNING_SECRET
            SLACK_BOT_TOKEN
            SLACK_LOGGING_LEVEL
            SLACK_CHANNEL
            GOOGLE_CALENDAR_ID
            GOOGLE_CLIENT_ID
            GOOGLE_CLIENT_SECRET
            GOOGLE_REFRESH_TOKEN
            GOOGLE_API_KEY
            SPREADSHEET_ID
            API_NINJAS_API_KEY
        env:
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_LOGGING_LEVEL: ${{ secrets.SLACK_LOGGING_LEVEL }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          API_NINJAS_API_KEY: ${{ secrets.API_NINJAS_API_KEY }}
